name: Make deployment

on: 
  push: 
    branches: 
      - master 
  
jobs: 
  make_build: 
    runs-on: ubuntu-18.04
    steps: 
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Install dependencies
      run : npm install --no-audit --no-fund --no-optional
    - name: Build 
      run : npm build-storybook 
    - uses: nwtgck/actions-netlify@v1.2
      with:
        publish-dir: './storybook-static'
        production-branch: master
        github-token: ${{ secrets.TOKEN_GITHUB }}
        deploy-message: "Deploy from GitHub Actions"
        enable-pull-request-comment: false
        enable-commit-comment: true
        overwrites-pull-request-comment: true
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      timeout-minutes: 1