name: 'Linter'
on:
  
  pull_request:

jobs:
  lint:
    name: "Run linter"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: "npm lint"
      run : npm run lint
     
  
